services:
  liji-app:
    image: zsw01442/liji:latest
    container_name: liji
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=/app/data
    restart: unless-stopped

# 项目名称
name: liji